apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  KAFKA_BROKER_1: "my-cluster-kafka-bootstrap:9092"
  KAFKA_CLIENT_ID: "workers-client"
  KAFKA_TOPIC_NAME: "SBOM_requests"
  JWT_SECRET: {{ .Values.secret }}