apiVersion: v1
kind: Service
metadata:
  name: {{ include "syfter-gql.fullname" . }}
  labels:
    {{- include "syfter-gql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    {{- include "syfter-gql.selectorLabels" . | nindent 4 }}
